test_size: 64
num_saving_steps: 10
gradient_checkpointing: True
trainer:
  dataloader_num_workers: 2
  eval_accumulation_steps: 4
  gradient_accumulation_steps: 1
  num_train_epochs: 1
  weight_decay: 0.1
  warmup_ratio: 0.05
  learning_rate: 1e-4
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  bf16: True
  report_to: "none"
lora: 
  lora_alpha: 64
  lora_dropout: 0.1
  r: 32
  bias: "none"
  task_type: "CAUSAL_LM"
