train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.Wikipedia2023
            split: "train"
            data_path: "/nfs/data/calmar/amyrzakha/data/wiki2023/chunked_dataset.tsv"
    query: 
        init_args:
            _target_: modules.dataset_processor.Frames
            split: "test"
test:
    doc: null
    query: null