train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.FramesOracle
            split: "train"
            data_path: "/nfs/data/calmar/amyrzakha/data/new_wiki/frames_oracle.csv"
    
    query: 
        init_args:
            _target_: modules.dataset_processor.Frames
            split: "test"
test:
    doc: null
    query: null