train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.Wikipedia2025
            split: "train"
            data_path: "/nfs/data/calmar/amyrzakha/new_wiki/enwiki-6-3.tsv"
    
    query: 
        init_args:
            _target_: modules.dataset_processor.Frames
            split: "test"
test:
    doc: null
    query: null