train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.processors.dataset_processor.MsMarcoCorpus
            split: "dev"
    
    query:
        init_args:
            _target_: modules.processors.dataset_processor.MsMarcoQueries
            split: "train"

    #query:
    #    init_args:
    #        _target_: modules.processors.msmarco_dataset_processor.MsMarcoFullDocQueries
    #        split: "train"
test:
    doc: null
    query: null