train:
    doc: null
    query: null
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.NarrativeQA_full
            split: "test"
    query: 
        init_args:
            _target_: modules.dataset_processor.NarrativeQA_full
            split: "test"
test:
    doc: null
    query: null